force-app/main/default/objects/VoiceCallTypeTemplate__mdt/VoiceCallTypeTemplate__mdt.object-meta.xml
<CustomObject>
    <description>Defines a configuration for a testing scenario to simulate a VoiceCall</description>
    <label>Voice Call Type Template</label>
    <pluralLabel>Voice Call Type Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <description>Branch Code (External Id)</description>
    <label>Branch</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <description>What kind of call is this?</description>
    <label>Call Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/FromPhone__c.field-meta.xml
<CustomField>
    <fullName>FromPhone__c</fullName>
    <description>From this Phone number</description>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/IVR_Authenticated__c.field-meta.xml
<CustomField>
    <fullName>IVR_Authenticated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the caller been authenticated in the IVR?</description>
    <label>IVR Authenticated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/IVR_Caller_Identified__c.field-meta.xml
<CustomField>
    <fullName>IVR_Caller_Identified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Did the IVR identify the customer?</description>
    <label>IVR Caller Identified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/IVR_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>IVR_Company_Code__c</fullName>
    <description>IVR identified Company Code (External Id)</description>
    <label>IVR Company Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/IVR_Contact_External_Id__c.field-meta.xml
<CustomField>
    <fullName>IVR_Contact_External_Id__c</fullName>
    <description>External Id of the Contact identified by the IVR</description>
    <label>IVR Contact External Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/ScenarioNumber__c.field-meta.xml
<CustomField>
    <fullName>ScenarioNumber__c</fullName>
    <label>Scenario Number</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/ToPhone__c.field-meta.xml
<CustomField>
    <fullName>ToPhone__c</fullName>
    <description>To Phone Number</description>
    <label>To Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/VoiceCallTypeTemplateListController.cls
/**
 * Custom List Controller for VoiceCallTypeTemplate
 **/ 
public class VoiceCallTypeTemplateListController {
    // ApexPages.StandardSetController must be instantiated
    // for standard list controllers
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [select id, developername, scenarioNumber__c
                     , CallType__c, FromPhone__c, ToPhone__c
                     , IVR_Caller_Identified__c, IVR_Authenticated__c
                     , IVR_Company_Code__c, Branch__c, IVR_Contact_External_Id__c
                     FROM VoiceCallTypeTemplate__mdt Order By scenarioNumber__c]));
            }
            return setCon;
        }
        set;
    }

    // Initialize setCon and return a list of records
    public List<VoiceCallTypeTemplate__mdt> getTemplates() {
        return (List<VoiceCallTypeTemplate__mdt>) setCon.getRecords();
    }
}