force-app/main/default/objects/Account/fields/IID__c.field-meta.xml
<CustomField>
    <fullName>IID__c</fullName>
    <externalId>true</externalId>
    <label>IIID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/UCM_Row_Id__c.field-meta.xml
<CustomField>
    <fullName>UCM_Row_Id__c</fullName>
    <externalId>true</externalId>
    <label>UCM Row Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/GC_Branch_Code__c.field-meta.xml
<CustomField>
    <fullName>GC_Branch_Code__c</fullName>
    <description>Received from the IVR for inbound voice calls.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/GC_Caller_Identified__c.field-meta.xml
<CustomField>
    <fullName>GC_Caller_Identified__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Caller Identified</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/GC_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>GC_Client_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/GC_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>GC_Company_Code__c</fullName>
    <description>ADP Company Code from UCM (pulled from all SORs) - passed to the Voice</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/GC_Conversation_Id__c.field-meta.xml
<CustomField>
    <fullName>GC_Conversation_Id__c</fullName>
    <description>GenCloud Conversation/Interaction/Transaction Id of actual voice call</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Conversation Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/GC_IVR_Language__c.field-meta.xml
<CustomField>
    <fullName>GC_IVR_Language__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IVR Language</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/GC_Menu_Selected__c.field-meta.xml
<CustomField>
    <fullName>GC_Menu_Selected__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>IVR Menu Selected</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCall/fields/IVR_AUTHENTICATED__c.field-meta.xml
<CustomField>
    <fullName>IVR_AUTHENTICATED__c</fullName>
    <description>Yes or No</description>
    <encryptionScheme>None</encryptionScheme>
    <label>IVR_AUTHENTICATED</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/VoiceCallTypeTemplate__mdt.object-meta.xml
<CustomObject>
    <description>Defines a configuration for a testing scenario to simulate a VoiceCall</description>
    <label>Voice Call Type Template</label>
    <pluralLabel>Voice Call Type Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <description>Branch Code (External Id)</description>
    <label>Branch</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <description>What kind of call is this?</description>
    <label>Call Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/FromPhone__c.field-meta.xml
<CustomField>
    <fullName>FromPhone__c</fullName>
    <description>From this Phone number</description>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/IVR_Authenticated__c.field-meta.xml
<CustomField>
    <fullName>IVR_Authenticated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the caller been authenticated in the IVR?</description>
    <label>IVR Authenticated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/IVR_Caller_Identified__c.field-meta.xml
<CustomField>
    <fullName>IVR_Caller_Identified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Did the IVR identify the customer?</description>
    <label>IVR Caller Identified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/IVR_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>IVR_Company_Code__c</fullName>
    <description>IVR identified Company Code (External Id)</description>
    <label>IVR Company Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/IVR_Contact_External_Id__c.field-meta.xml
<CustomField>
    <fullName>IVR_Contact_External_Id__c</fullName>
    <description>External Id of the Contact identified by the IVR</description>
    <label>IVR Contact External Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/ScenarioNumber__c.field-meta.xml
<CustomField>
    <fullName>ScenarioNumber__c</fullName>
    <label>Scenario Number</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VoiceCallTypeTemplate__mdt/fields/ToPhone__c.field-meta.xml
<CustomField>
    <fullName>ToPhone__c</fullName>
    <description>To Phone Number</description>
    <label>To Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/VCUtil.cls
public class VCUtil {
    public static VoiceCall scenario(integer scenario) {
        List<VoiceCallTypeTemplate__mdt> configs = [select id, scenarioNumber__c, CallType__c, FromPhone__c, ToPhone__c
                                                    , IVR_Caller_Identified__c, IVR_Authenticated__c
                                                    , IVR_Company_Code__c, Branch__c, IVR_Contact_External_Id__c
                                             from VoiceCallTypeTemplate__mdt
                                             where ScenarioNumber__c = :scenario];
        
        if (configs.isEmpty()) {
            System.Debug('Scenario not found: ' + scenario);
            return null;
        }
                
        return createVC(configs[0]);
    }
    
    private static Id createAccount(final String companyCode) {
        List<Account> theAccounts = [select id from Account 
                                     Where IID__c = :companyCode 
                                     LIMIT 1];  // Unique External ID
        
        Account result=null;
        
        if (theAccounts.isEmpty()) {
            // Create it on the fly
            //### TODO Ensure that it's owned by the integration user
            result = new Account(IID__c=companyCode, name='Test Company: '+ companyCode);
            insert result;
            
        } else {
            result = theAccounts[0];
        }
        
        
        return result.Id;
    }
    
     private static Id createContact(final Id acctId, final String contactExtId) {
        List<Contact> theContacts = [select id, accountId from Contact 
                                     Where UCM_Row_Id__c  = :contactExtId 
                                     LIMIT 1];  // Unique External ID
        
        Contact result=null;
        
        
        if (theContacts.isEmpty()) {
            // Create it on the fly
            //### TODO Ensure that it's owned by the integration user
            result = new Contact(UCM_Row_Id__c=contactExtId
                                 , AccountId=acctId
                                 , FirstName='Test Contact: '+ contactExtId
                                 , LastName='TestContactLastname');
            insert result;
            
        } else {
            result = theContacts[0];
        }
        
        
        return result.Id;
    }

    
    private static VoiceCall createVC(final VoiceCallTypeTemplate__mdt config) { 
        final Id acctId = createAccount(config.IVR_Company_Code__c);
        final Id contactId = createContact(acctId,config.IVR_Contact_External_Id__c);
        
        VoiceCall myVC = new VoiceCall();
        myVC.CallCenterId = VCUtil.getCallCenter(); 
        myVC.CallType= config.CallType__c; 
        myVC.CallDisposition = 'Connected';
        myVC.FromPhoneNumber= config.FromPhone__c ;
        myVC.VendorCallKey='123'+ System.now();
        myVC.VendorType='ContactCenter';
        myVC.ToPhoneNumber=config.ToPhone__c;
        myVC.CallStartDateTime= Datetime.now()-300;
        myVC.CallEndDateTime= Datetime.now();
        // Custom fields
        myVC.GC_Branch_Code__c  = config.Branch__c;
        myVC.GC_Caller_Identified__c  = config.IVR_Caller_Identified__c.toString();
        myVC.IVR_AUTHENTICATED__c  = config.IVR_Authenticated__c.toString();
        myVC.GC_Company_Code__c = config.IVR_Company_Code__c;
        myVC.GC_Client_Id__c = config.IVR_Contact_External_Id__c;
        
        insert myVC;
        
        System.debug('VoiceCall: ' + myVC);
        return myVC;
    }
    
    private static Id getCallCenter() {
        User runningUser = [select id, callCenterId From User where Id = :UserInfo.getUserId()];
        return runningUser.callCenterId;
    }
    
    public static void createVC(final String fromNumber) {
        VoiceCall myVC = new VoiceCall();
        //myVC.CallCenterId = '04vDC000000Kz6lYAC';
        myVC.CallType='Inbound';
        myVC.CallDisposition = 'Connected';
        myVC.FromPhoneNumber= fromNumber;
        myVC.VendorCallKey='123'+ System.now();
        myVC.VendorType='ContactCenter';
        myVC.ToPhoneNumber='8006676389273';
        myVC.CallStartDateTime= Datetime.now()-300;
        myVC.CallEndDateTime= Datetime.now();
        
        insert myVC;
        
        System.debug('VoiceCall: ' + myVC);
    }
}

/**
 * {
    "CallCenterId": "04vDC000000Kz6lYAC",
    "CallType": "Inbound",
    "FromPhoneNumber": "{{FromPhoneNumber}}",
    "GC_Caller_Identified__c": "No",
    "GC_Conversation_Id__c": "494be377-957c-4f1f-a61d-f29f674d88d5",
    "GC_IVR_Language__c": "English",
    "GC_Menu_Selected__c": "AnythingElse",
    "IVR_AUTHENTICATED__c": "No",
    "VendorCallKey": "8e54d47a-d08e-4e0f-9ec5-aadb9456b0eb:66163a6d-202b-4698-9369-69864c8e2740",
    "VendorType": "ContactCenter",
    "CallStartDateTime": "2024-06-11T19:19:29.000Z",
    "CallEndDateTime": "2024-06-11T19:29:29.000Z",
    "ToPhoneNumber": "+13160070070"
  }
 * 
 **/